# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6cab8fac42bd569f60954777fcee9cabefed7bcfbbc905c5127f82f3ce8c3857a30f8d2c967bf688a84d73713a1d84dd5dd173f40c68fe4ff06645f3acb2ba3

test:
  secret_key_base: 9dc465e4a4831c6da8beb344d95805119794f766ef77827984efb64723959956fb120803786d53ae8b50c6a2baca57250b385c113a77354ac10095fe6754d24b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
